### ISSUE TITLE
Explain -s option for pytest

### ISSUE THREAD

**Issue by revelutions** [basdijkstra/requests-workshop#2]
If I am just looking at the slides, it would be good to explain the "-s" option on Slide 51 - Posting a JSON request body.  That would avoid my having to search.

**Comment by basdijkstra** [comment]
Thanks for reporting this, @nilanjenator. I've added an explanation to the slides, please check out the latest version.

**Comment by basdijkstra** [comment]
No further comments received, so I'm closing this issue.
